### ISSUE TITLE
Incorrect report?

### ISSUE THREAD

**Issue by peterjaap** [sansecio/composer-integrity-plugin#9] opened 2023-04-24 08:02 UTC
I see this modules listed that are mismatched;

```
|   ⨉    | magento/module-bundle                           | 101.0.6     | D4DED34CE8057AA8 | 773E9097D362FE84 |     4%     |       No       |
|   ⨉    | magento/module-catalog-graph-ql                 | 100.4.6     | 4DA8F553B307EF1E | 4CCCD8B580769DA6 |     5%     |       No       |
|   ⨉    | magento/module-catalog-search                   | 102.0.6     | 0CC44559B51259B6 | 43B4A3611F12E768 |     4%     |       No       |
|   ⨉    | magento/module-catalog-widget                   | 100.4.6     | 323627DDBB3FC7B4 | A501A94E3F212CE1 |     4%     |       No       |
|   ⨉    | magento/module-checkout                         | 100.4.6     | D6F1DD5B129D6114 | 0FB6D1F089913564 |     4%     |       No       |
|   ⨉    | magento/module-directory-graph-ql               | 100.4.4     | 9FD0061629AF1A32 | 8D44305C732BE059 |     0%     |       No       |
|   ⨉    | magento/module-eav                              | 102.1.6     | 6AED23DB20C51665 | F7D8330F33A07B25 |     0%     |       No       |
|   ⨉    | magento/module-elasticsearch                    | 101.0.6     | 8157285B3E2C0A79 | D313E325B8F9BFCB |     4%     |       No       |
|   ⨉    | magento/module-elasticsearch-7                  | 100.4.6     | 85BA211B8AA3DD6E | D6FAAEE4D086FE3D |     4%     |       No       |
|   ⨉    | magento/module-graph-ql                         | 100.4.6     | AE16963F6D69039B | 390A36E2F3339E05 |     5%     |       No       |
|   ⨉    | magento/module-import-export                    | 101.0.6     | 2E117BC0BB1C2C9F | 2F65898970E9B77F |     0%     |       No       |
|   ⨉    | magento/module-message-queue                    | 100.4.6     | 1DABE71D03907454 | F9DF76EEC3662133 |     0%     |       No       |
|   ⨉    | magento/module-mysql-mq                         | 100.4.4     | 9F7A4DB5DD7ECF91 | E35F959FCFC40FDA |     0%     |       No       |
|   ⨉    | magento/module-product-alert                    | 100.4.5     | 1465355D8E610DFB | C6C2FFEC27A78877 |     4%     |       No       |
|   ⨉    | magento/module-quote-graph-ql                   | 100.4.6     | 96EDF305535226C1 | 17F30AA09A9FD0CA |     5%     |       No       |
|   ⨉    | magento/module-reports                          | 100.4.6     | 36D9348DA9C6E81D | 5907444B5E828498 |     4%     |       No       |
|   ⨉    | magento/module-review-graph-ql                  | 100.4.2     | BAB5B226681F548D | 15F9CF4C08CDAD87 |     5%     |       No       |
|   ⨉    | magento/module-store                            | 101.1.6     | 3146DA303469ABA9 | 714E8EE70A1329EF |     0%     |       No       |
|   ⨉    | magento/module-store-graph-ql                   | 100.4.4     | A91424DDC84DA5A1 | 8CBDD61F8830F633 |     0%     |       No       |
|   ⨉    | magento/module-ui                               | 101.2.6     | CC28F53B71A481AC | 5DB3707A3D8A640C |     4%     |       No       |
|   ⨉    | magento/module-url-rewrite                      | 102.0.5     | C349A2F39B8A46F5 | 60F230241E2F7129 |     0%     |       No       |
```

These come straight from the Magento repository, and I manually verified some of them. Why is there a mismatch on these with such a low percentage?

**Comment by danslo** [comment] 2023-04-24 09:25
Could you zip one of these up? I want to check whether this is a bug in the hashing algo, or if there's another issue (actual difference in files/structure)

**Comment by peterjaap** [comment] 2023-04-24 09:28
[elastic7.zip](https://github.com/sansecio/composer-integrity-plugin/files/11308807/elastic7.zip)

Here you go

**Comment by danslo** [comment] 2023-04-24 10:00
Thanks. So in my clean install of 2.4.6 I get:

```
|   ✓    | magento/module-elasticsearch-7                                    | 100.4.6   | 85BA211B8AA3DD6E | 802BBF85D3AA12C3 |    94%     |
```

While you get:
```
|   ⨉    | magento/module-elasticsearch-7                  | 100.4.6     | 85BA211B8AA3DD6E | D6FAAEE4D086FE3D |     4%     |       No       |
```


```
diff -qr ~/Downloads/vendor/magento/module-elasticsearch-7 vendor/magento/module-elasticsearch-7
Files /Users/daniel/Downloads/vendor/magento/module-elasticsearch-7/Model/Client/Elasticsearch.php and vendor/magento/module-elasticsearch-7/Model/Client/Elasticsearch.php differ
Files /Users/daniel/Downloads/vendor/magento/module-elasticsearch-7/SearchAdapter/Adapter.php and vendor/magento/module-elasticsearch-7/SearchAdapter/Adapter.php differ
```


```
diff /Users/daniel/Downloads/vendor/magento/module-elasticsearch-7/Model/Client/Elasticsearch.php vendor/magento/module-elasticsearch-7/Model/Client/Elasticsearch.php
382,403d381
<
<     /**
<      * Open point in time
<      *
<      * @param array $params
<      * @return array
<      */
<     public function openPointInTime(array $params = []): array
<     {
<         return $this->getElasticsearchClient()->openPointInTime($params);
<     }
<
<     /**
<      * Close point in time
<      *
<      * @param array $params
<      * @return array
<      */
<     public function closePointInTime(array $params = []): array
<     {
<         return $this->getElasticsearchClient()->closePointInTime($params);
<     }
```

My composer.lock contains:
https://repo.magento.com/archives/magento/module-elasticsearch-7/magento-module-elasticsearch-7-100.4.6.0.zip


```
$ curl -H "User-Agent: Composer/2.0.7 (Linux; 4.15.0-20-generic; PHP 7.2.24; curl 7.58.0)" --user USERNAME:PASSWORD https://repo.magento.com/archives/magento/module-elasticsearch-7/magento-module-elasticsearch-7-100.4.6.0.zip -o /tmp/elastic/elastic.zip
```

```
$ diff -qr ~/Downloads/vendor/magento/module-elasticsearch-7 /tmp/elastic
Files /Users/daniel/Downloads/vendor/magento/module-elasticsearch-7/Model/Client/Elasticsearch.php and /tmp/elastic/Model/Client/Elasticsearch.php differ
Files /Users/daniel/Downloads/vendor/magento/module-elasticsearch-7/SearchAdapter/Adapter.php and /tmp/elastic/SearchAdapter/Adapter.php differ
```

So I'm still convinced your elastic is different from the offical Magento Repo. I also tried mage-os repo and similar story.

**Comment by peterjaap** [comment] 2023-04-24 10:13
That is weird, since this comes from the mage-os repo; https://mirror.mage-os.org/#magento/module-elasticsearch-7

This file comes straight out of our Private Packagist; 
[magento_module-elasticsearch-7_100.4.6.0_.zip](https://github.com/sansecio/composer-integrity-plugin/files/11309228/magento_module-elasticsearch-7_100.4.6.0_.zip)

**Comment by peterjaap** [comment] 2023-04-24 10:15
I also can't seem to find any mention of `openPointInTime` in the Magento codebase https://github.com/search?q=repo%3Amagento%2Fmagento2%20openPointInTime&type=code

**Comment by danslo** [comment] 2023-04-24 10:17
> That is weird, since this comes from the mage-os repo; https://mirror.mage-os.org/#magento/module-elasticsearch-7
> 
> This file comes straight out of our Private Packagist; [magento_module-elasticsearch-7_100.4.6.0_.zip](https://github.com/sansecio/composer-integrity-plugin/files/11309228/magento_module-elasticsearch-7_100.4.6.0_.zip)

Is there a way to evict packages from your private packagist, so that it gets re-cached?

It wouldn't be the first time Magento released a package and then quietly changed it under the same version afterwards

**Comment by peterjaap** [comment] 2023-04-24 10:23
I removed & reinitialized it, here's the download; 
[magento_module-elasticsearch-7_100.4.6.0_ (1).zip](https://github.com/sansecio/composer-integrity-plugin/files/11309311/magento_module-elasticsearch-7_100.4.6.0_.1.zip)

**Comment by danslo** [comment] 2023-04-24 10:30
> I removed & reinitialized it, here's the download; [magento_module-elasticsearch-7_100.4.6.0_ (1).zip](https://github.com/sansecio/composer-integrity-plugin/files/11309311/magento_module-elasticsearch-7_100.4.6.0_.1.zip)

This one seems more like it. Now try removing local composer cache, doing a `composer install`, and did the hash change?

**Comment by peterjaap** [comment] 2023-04-24 10:32
@danslo, jup, gone now!

So it appears I might have to reinitialize my complete Composer package cache on Private Packagist...

**Comment by danslo** [comment] 2023-04-24 10:33
> @danslo, jup, gone now!
> 
> So it appears I might have to reinitialize my complete Composer package cache on Private Packagist...

Probably, thank you Magento for quietly changing packages... :sweat_smile: 

At least we know the integrity check is doing its job...

**Comment by danslo** [comment] 2023-04-24 10:34
At least we know the integrity check is doing its job...

**Comment by danslo** [comment] 2023-04-24 12:16
So let's close this, as it looks like it's working as intended. 

Let's keep the other issue open, as we might have to turn and twist some treshold numbers.

**Closed as completed by danslo** 2023-04-24 12:16 UTC
